language: node_js
node_js:
- '16.8.0'

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  local-dir: build
  on:
    branch: master
