export {
  setTokenAxios,
  getTags,
  login,
  signup,
  auth,
  updateUser,
  getAllArticles,
  getArticlesByAuthor,
  getArticlesByTag,
  deleteArticle,
  setArticleAsFavorite,
  getFavoritedArticles,
  getFeedArticles,
  getArticle,
  deleteArticleAsFavorite,
  updateArticle,
  createArticle,
  createComment,
  deleteComment,
  getCommentsForArticle,
  followUser,
  getProfile,
  unfollowUser
} from "./api";
